require("config.options")
-- require("config.autocommands")
require("config.lazy")
require("config.mini-nvim")
require("config.keymaps")
require("config.nvim-telescope")
require("config.lualine")
require("config.nvim-treesitter-config")
require("config.lsp-config")
require("config.debugger")
require("config.whichkey") -- for which key mapping informations
